spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teach_time_management
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect